# Lista 2
## Magdalena Ryś

In [1]:
import numpy as np #używane jedynie do porównywania wyników

### Zadania 1-3

Oddane na kartce na zajęciach

### FUNKCJE POMOCNICZE ZASTĘPUJĄCE METODY W NUMPY:

In [2]:
def identity(n: int) -> list[list[int]]:
    """
    Function:
        funkcja generująca macierz jednostkową
    Inpput:
        n (int) - wymiar macierzy
    Output:
        (list of lists) - macierz jednostkowa o podanych wymiarach
    """
    return [[1 if i == j else 0 for j in range(n)] for i in range(n)]

def print_matrix(matrix: list[list[float]]):
    """
    Function:
        funkcja wspomagająca wywoływanie macierzy w celu uniknięcia wyprintowania jej w jednej linijce
    Input:
        matric (list of lists) - macierz"""
    for el in matrix:
        print(el)

def matrix_x_vector(matrix: list[list[float]], vector: list[float]) -> list[list[float]]:
    """
    Function:
        funkcja mnożąca macierz razy wektor
    Input:
        matrix (list of lists) - macierz
        vector (list) - wektor
    Output:
        result (list of lists) - wynik mnożenia
    """
    n = len(matrix)
    result = [0 for _ in range(n)]
    
    for i in range(n):
        for j in range(len(vector)):
            result[i] += matrix[i][j] * vector[j]
    
    return result

### FUNKCJA OBLICZAJĄCA WYZNACZNIK MACIERZY

In [3]:
def determinant(matrix: list[list[float]]) -> float:
    '''
    Function:
        Funkcja obliczająca wyznacznik podanej macierzy
    Input:
        matrix (list of lists) - macierz, której wyznacznik chcemy obliczyć
    Output:
        det (float) - wyznacznik macierzy
    '''
    A = [row[:] for row in matrix]  
    n = len(A)
    det = 1

    for i in range(n - 1):
        if A[i][i] == 0:
            for j in range(i + 1, n):
                if A[j][i] != 0:
                    A[i], A[j] = A[j], A[i]
                    det *= -1 
                    break
            else:
                return 0

        for k in range(i + 1, n):
            if A[k][i] != 0:
                factor = A[k][i] / A[i][i]
                for col in range(i, n):
                    A[k][col] -= factor * A[i][col]

    for i in range(n):
        det *= A[i][i] 

    return det


### FUNKCJA WYKORZYSTUJĄCA METODĘ ELIMINACJI GAUSSA

In [4]:
def gauss_elimination(matrix_A: list[list[float]], matrix_b: list[float]) -> list[float]:
    '''
    Function:
        Funkcja rozwiązująca równanie za pomocą metody eliminacji gaussa
    Input:
        matrix_A (list of lists) - macierz A
        matrix_b (list) - lista b
    Output:
        x (list) - macierz rozwiązań
    '''
    A = [row[:] for row in matrix_A]  
    b = matrix_b[:]  
    n = len(A)

    for i in range(n - 1):
        if A[i][i] == 0: 
            for j in range(i + 1, n):
                if A[j][i] != 0:
                    A[i], A[j] = A[j], A[i]
                    b[i], b[j] = b[j], b[i]
                    break

        for k in range(i + 1, n):
            if A[k][i] != 0:
                factor = A[k][i] / A[i][i]
                for c in range(i, n):
                    A[k][c] -= factor * A[i][c]
                b[k] -= factor * b[i]

    x = [0] * n
    for i in range(n - 1, -1, -1):
        sum_ax = 0
        for j in range(i + 1, n):
            sum_ax += A[i][j] * x[j]
        x[i] = (b[i] - sum_ax) / A[i][i]

    return x

In [7]:
A = np.array([[1, 1, 1],
              [2, -3, 4],
              [3, 4, 5]], dtype=float)

b = [9, 13, 40]

print(gauss_elimination(A,b))

[np.float64(1.0), np.float64(3.0), np.float64(5.0)]


### FUNKCJA OBLICZAJĄCA MACIERZ ODWROTNĄ DO MACIERZY A

In [ ]:
def invertible_matrix(matrix: list[list[float]]) -> list[list[float]]:
    '''
    Function:
        Funkcja obliczająca macierz odwrotą
    Input:
        matrix (list of lists) - macierz, której macierz odwrotną
    Output:
        I (list of lists) - obliczona macierz odwrotna
    '''
    A = [row[:] for row in matrix]
    n = len(A)
    I = identity(n)

    for i in range(n):
        if A[i][i] == 0:
            for j in range(i + 1, n):
                if A[j][i] != 0:
                    A[i], A[j] = A[j], A[i]
                    I[i], I[j] = I[j], I[i]
                    break
            else:
                raise ValueError("Macierz osobliwa nie ma macierzy odwrotnej")

        factor = A[i][i]
        for c in range(n):
            I[i][c] /= factor
            A[i][c] /= factor

        for k in range(i + 1, n):
            if A[k][i] != 0:
                factor = A[k][i]
                for c in range(n):
                    I[k][c] -= factor * I[i][c]
                    A[k][c] -= factor * A[i][c]

    for i in range(n - 1, -1, -1):
        for j in range(i - 1, -1, -1):
            factor = A[j][i]
            for c in range(n):
                I[j][c] -= factor * I[i][c]
                A[j][c] -= factor * A[i][c]

    return I

### FUNKCJA ZAMIENIAJĄCA PUNKTY NA MACIERZ

In [ ]:
def points_to_matrix(points: list[tuple]) -> tuple[list[list[float]], list[float]]:
    '''
    Function:
        Funkcja zamieniająca punkty przez które przechodzi wielomian na macierze do rozwiązania metodą gaussa
    Input:
        points (list of tuples) - punkty przez które przechodzi wielomian
    Output:
        matrix_A (list of lists) - macierz A
        matrix_b (list) - lista b
    '''
    n = len(points)
    A = [[0 for _ in range(n)] for _ in range(n)]
    b = [0 for _ in range(n)]

    for i in range(n):
        for j in range(n):
            A[i][j] = points[i][0] ** j  
        b[i] = points[i][1]

    return A, b

### Zadanie 4

Rozwiąż układ równań $Ax = b$ 

In [ ]:
A4 = [[0, 0, 2, 1, 2], [0, 1, 0, 2, -1], [1, 2, 0, -2, 0], [0, 0, 0, -1, 1], [0, 1, -1, 1, -1]]
b4 = [1, 1, -4, -2, -1]

print("Rozwiązanie metodą eliminacji gaussa:", gauss_elimination(A4, b4))
print("Rozwiązanie funkcją wbudowaną numpy: ", np.linalg.solve(A4, b4))

Rozwiązanie metodą eliminacji gaussa: [2.0, -2.0, 1.0, 1.0, -1.0]
Rozwiązanie funkcją wbudowaną numpy:  [ 2. -2.  1.  1. -1.]


W celu rozwiązania podanego układu równań wykorzystano zaimplementowaną wcześniej metodę eliminacji gaussa. Jak widać, otrzymane rozwiązania pokrywają się z tymi wygenerowanymi przez funkcję wbudowaną pakietu numpy.

### Zadanie 5
Wyznacz współczynniki wielomianu
$y = a_0 + a_1 \ x + a_2 \ x^2 + a_3 \ x^3 + a_4 \ x^4 $, który przechodzi przez punkty $(0, -1), (1, 1), (3, 3), (5, 2)$ i $(6, -1)$.

Aby wyznaczyć współczynniki $a_1, a_2, a_3, a_4$ wielomianu wykorzystujemy układ równań, który następnie rozwiążemy zaimplementowaną wcześniej metodą eliminacji Gaussa. Do równania wielomianu podstawiamy podane punkty otrzymując układ pięciu równań:

\begin{cases}
  a_0 = -1, \\
  a_0 + a_1 + a_2 + a_3 + a_4 = 1, \\
  a_0 + 3a_1 + 9a_2 + 27a_3 + 81a_4 = 3, \\
  a_0 + 5a_1 + 25a_2 + 125a_3 + 625a_4 = 2, \\
  a_0 + 6a_1 + 36a_2 + 216a_3 + 1296a_4 = -1.
\end{cases}

którego wektor rozwiązań jest szukanymi przez nas wspołczynnikami $a_1, a_2, a_3, a_4$.

In [ ]:
points = [(0, -1), (1, 1), (3, 3), (5, 2), (6, -2)]
A5, b5 = points_to_matrix(points)

print("Rozwiązanie metodą eliminacji gaussa:", gauss_elimination(A5, b5))
print("Rozwiązanie funkcją wbudowaną numpy: ", np.linalg.solve(A5,b5))

Rozwiązanie metodą eliminacji gaussa: [-1.0, 2.6833333333333336, -0.8750000000000003, 0.21666666666666679, -0.02500000000000001]
Rozwiązanie funkcją wbudowaną numpy:  [-1.          2.68333333 -0.875       0.21666667 -0.025     ]


### Zadanie 6
Rozwiąż układ równań $Ax = b$. Oblicz det $A$ i $Ax$. Co powiesz o dokładności rozwiązania?

In [ ]:
A6 = [[3.5, 2.77, -0.76, 1.80], [-1.80, 2.68, 3.44, -0.09], [0.27, 5.07, 6.90, 1.61], [1.71, 5.45, 2.68, 1.71]]
b6 = [7.31, 4.23, 13.85, 11.55]

x = gauss_elimination(A6, b6)
Ax = matrix_x_vector(A6, x)

print("Rozwiązanie metodą eliminacji Gaussa:        ", gauss_elimination(A6, b6))
print("Rozwiązanie funkcją wbudowaną numpy:         ", np.linalg.solve(A6, b6), "\n")
print("Wyznacznik macierzy A wg funkcji determinant:", determinant(A6))
print("Wyznacznik macierzy A wg numpy:              ", np.linalg.det(A6), "\n")
print("Obliczona wartość Ax:                        ", Ax)

Rozwiązanie metodą eliminacji Gaussa:         [1.0000000000000442, 1.0000000000000102, 1.0000000000000129, 0.9999999999999036]
Rozwiązanie funkcją wbudowaną numpy:          [1. 1. 1. 1.] 

Wyznacznik macierzy A wg funkcji determinant: -0.22579734000001275
Wyznacznik macierzy A wg numpy:               -0.2257973399999901 

Obliczona wartość Ax:                         [7.31, 4.230000000000001, 13.849999999999998, 11.550000000000002]


Jak widać, otrzymane za pomocą metody eliminacji gaussa rozwiązania nieznacznie różnią się od tych z biblioteki numpy. Wynika to z błędów zaokrągleń w obliczeniach numerycznych przy użyciu liczb zmiennoprzecinkowych, oraz kumulacji błędów wynikającej ze złożoności obliczeń. Błędy te są jednak nieznaczne - w przypadku wektorów rozwiązań są to różnice rzędu $10^{14}$, natomiast dla wyznacznika macierzy $A$ $10^8$. Różnice między obliczoną wartością $Ax$ a wektorem $b$ są rzędu nawet $10^{16}$.

### Zadanie 7
Rozwiąż układ równań

In [ ]:
A7 = [[10, -2, -1, 2, 3, 1, -4, 7], 
      [5, 11, 3, 10, -3, 3, 3, -4], 
      [7, 12, 1, 5, 3, -12, 2, 3], 
      [8, 7, -2, 1, 3, 2, 2, 4],
      [2, -15, -1, 1, 4, -1, 8, 3],
      [4, 2, 9, 1, 12, -1, 4, 1],
      [-1, 4, -7, -1, 1, 1, -1, -3],
      [-1, 3, 4, 1, 3, -4, 7, 6]]

b7 = [0, 12, -5, 3, -25, -26, 9, -7]

print("Rozwiązanie metodą eliminacji gaussa:", gauss_elimination(A7, b7))
print("Rozwiązanie funkcją wbudowaną numpy: ", np.linalg.solve(A7,b7))

Rozwiązanie metodą eliminacji gaussa: [-0.9999999999999986, 0.9999999999999992, -0.9999999999999996, 0.9999999999999991, -1.0000000000000004, 0.9999999999999993, -0.9999999999999991, 0.9999999999999987]
Rozwiązanie funkcją wbudowaną numpy:  [-1.  1. -1.  1. -1.  1. -1.  1.]


### Zadanie 8
Znajdź macierz odwrotną do macierzy. Zwróć uwaagę na kształt $A^{-1}$. Czy jest trójdiagonalna?

In [ ]:
A8 = [[2, -1, 0, 0, 0, 0],
      [-1, 2, -1, 0, 0, 0],
      [0, -1, 2, -1, 0, 0],
      [0, 0, -1, 2, -1, 0],
      [0, 0, 0, -1, 2, -1],
      [0, 0, 0, 0, -1, 5]]

print_matrix(invertible_matrix(A8))
print("\n", np.linalg.inv(A8))

[0.84, 0.6799999999999999, 0.5199999999999998, 0.36, 0.19999999999999998, 0.04]
[0.6799999999999999, 1.3599999999999999, 1.0399999999999996, 0.72, 0.39999999999999997, 0.08]
[0.5199999999999999, 1.0399999999999998, 1.5599999999999996, 1.08, 0.6, 0.12000000000000001]
[0.36, 0.72, 1.0799999999999998, 1.4400000000000002, 0.8, 0.16000000000000003]
[0.19999999999999998, 0.39999999999999997, 0.5999999999999999, 0.8, 1.0, 0.2]
[0.039999999999999994, 0.07999999999999999, 0.11999999999999997, 0.16, 0.19999999999999998, 0.24]

 [[0.84 0.68 0.52 0.36 0.2  0.04]
 [0.68 1.36 1.04 0.72 0.4  0.08]
 [0.52 1.04 1.56 1.08 0.6  0.12]
 [0.36 0.72 1.08 1.44 0.8  0.16]
 [0.2  0.4  0.6  0.8  1.   0.2 ]
 [0.04 0.08 0.12 0.16 0.2  0.24]]


Otrzymana macierz nie jest trójdiagonalna, ale jest symetryczna. Mimo nieznacznych nidokładności możemy zauważyć, że otzrymany wynik pokrywa się z tym uzyskanym za pomocą biblioteki numpy.

### Zadanie 9

Znajdź macierz odwrotną do macierzy. Co powiesz o jakości tego rozwiązania?

In [ ]:
A9 = [[1, 3, -9, 6, 4],
      [2, -1, 6, 7, 1],
      [3, 2, -3, 15, 5],
      [8, -1, 1, 4, 2],
      [11, 1, -2, 18, 7]]

print(invertible_matrix(A9))

ValueError: Macierz osobliwa nie ma macierzy odwrotnej

In [ ]:
print(determinant(A9))

9.485745522397344e-13
1.9761969838327938e-14


Wyznacznik podanej macierzy wynosi zero (w wyniku niedokładności obliczeń powyżej otrzymano "prawie zero"), czyli macierz jest osobliwa, a więc nie posiada macierzy odwrotnej.